baseURL = "https://www.michanix.be"
languageCode = "en"
DefaultContentLanguage = "en"
title = "MichaniX Website"
theme = "anatole"
summarylength = 10
enableEmoji = true

# Enable Disqus
#disqusShortname = ""

# Google Analytics
googleAnalytics = "UA-171142842-1"

[params]
title = "MichaniX"
author = "Thomas Michem"
description = "Thomas Michem"
profilePicture = "images/profile.png"
profileLogo = "images/michanix.jpg"
keywords = ""
favicon = "favicons/"
customCss = []
mainSections = ["post"]

## Math settings
[params.math]
enable = false  # options: true, false. Enable math support globally, default: false. You can always enable math on per page.
use = "katex"  # options: "katex", "mathjax". default is "katex".

## Social links
[[params.socialIcons]]
icon = "fa-linkedin"
title = "Linkedin"
url = "https://www.linkedin.com/in/thomas-michem-2792656/"

[[params.socialIcons]]
icon = "fa-twitter"
title = "Twitter"
url = "https://twitter.com/michemt"

[[params.socialIcons]]
icon = "fa-github"
title = "GitHub"
url = "https://github.com/michem"

[[params.socialIcons]]
icon = "fa-envelope"
title = "e-mail"
url = "mailto:thomas.michem@michanix.be"

## Menu items

[menu]

  [[menu.main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[menu.main]]
  name = "Posts"
  weight = 200
  identifier = "posts"
  url = "/post/"

  [[menu.main]]
  name = "About"
  weight = 300
  identifier = "about"
  url = "/about/"
